male: 1
type: "1"
template: "template_user"
female: 0
date_format: "%m/%d/%Y"
date:
  formats:
    default: "%d/%m/%Y"
    short: "%b %d"
    long: "%B %d, %Y"
achievement:
  cancel_edit: "cancel_achievement_edit"
  cancel_new: "cancel_achievement_new"
certificate:
  maximum: 255
certificate_cancel:
  edit: "cancel_certificate_edit"
  new: "cancel_certificate_new"
selected: "1"
clubs:
  model:
    current_fall: "1"
    name_max_length: 150
    pos_max_length: 100
    cont_max_length: 5000
    cont_min_length: 20
experiences:
  cancel_edit: "cancel_experience_edit"
  cancel_new: "cancel_experience_new"
  model:
    name_max_length: 150
    company_max_length: 150
    detail_max_length: 5000
    detail_min_length: 20
pagination:
  jobs_perpage: 5
jobs:
  description:
    limit_show: 150
    maximum_length: 255
employers:
apply:
  image: 50
  page: 10
job:
  hundred: 100
  twenty: 21
  sixty: 61
  sixteen: 60
  fourty: 41
  fourteen: 40
  thirty: 30
  width: 10
  page: 10
activity:
  page: 10
bookmark:
  image: 50
  bookmarked: 0
  liked: 1
currency:
  dollar: "$"
  page: 5
placeholder:
  display_none: "display-none"
page_size:
  size: "A4"
send_cv:
  type: "application/pdf"
  inline: "inline"
img_cv: 155
text_area:
  rows: "10"
  cols: "30"
  rows_email: "20"
  cols_email: "30"
www: "www"
company:
  text_area:
    cols: 30
    rows: 7
inforappointment:
  agree: 1
  not_agree: 2
rspec:
  blank: ""
  job_spec:
    salary: 1500
    max_salary: 1000
    min_salary: 1200
counter:
  page_one: 1
  add_page: 1
  rm_page: 1
employers:
  company:
    text_area_cols: 2
    text_area_rows: 2
templates:
  page: 10
  member: 0
  user: 1
  textarea: 40
  url: "public/uploads/"
  upload: "/uploads/"
picture_user_width: 60
picture_user_height: 60
statuses: ["waitting", "review", "test", "interview", "offer", "joined"]
language:
  en: "en"
  vn: "vn"
frc:
  size: 25
